# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Petrovich-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Petrovich-demo

  target 'Petrovich-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Petrovich-demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetrovichTests' do
    inherit! :search_paths
    pod 'Nimble'
  end

end
